version: "3.7"
services:
    main:
        container_name: main
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
            - 9229:9229
        command: yarn start:debug
        links:
            - mysql
        env_file:
            - .env
        networks:
            - webnet
        depends_on:
            - redis
            - mysql
    redis:
        image: redis:5
        networks:
            - webnet
    mysql:
        image: mysql:5.7
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sermabud
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        networks:
            - webnet
networks:
    webnet:
volumes:
    mysql_data:
